/*
 * Stub implementations for cross-compilation targets.
 * Provides minimal implementations of clock functions
 * so that Leash can be cross-compiled to non-Linux targets.
 * 
 * Note: The Leash custom GC (gc.c) is linked separately,
 * so these stubs don't need to provide GC functions.
 */

#include <stdlib.h>
#include <time.h>
#include <stdint.h>
#include <sys/time.h>
#include <stdio.h>

/* Helper to get stdout portably */
FILE* _leash_get_stdout(void) {
    return stdout;
}

#ifndef __linux__
/* clock_gettime stub - use regular time functions */
int clock_gettime(int clk_id, struct timespec* tp) {
    struct timeval tv;
    if (gettimeofday(&tv, NULL) != 0) {
        return -1;
    }
    tp->tv_sec = tv.tv_sec;
    tp->tv_nsec = tv.tv_usec * 1000;
    return 0;
}
#endif

/* __chkstk - Windows stack checking function generated by LLVM */
#ifdef _WIN32
void __chkstk(void) {
    /* No-op */
}
#endif
