/*
 * Stub implementations for cross-compilation targets.
 * Provides minimal implementations of GC and clock functions
 * so that Leash can be cross-compiled to non-Linux targets.
 */

#include <stdlib.h>
#include <time.h>
#include <stdint.h>
#include <sys/time.h>
#include <stdio.h>

/* Helper to get stdout portably */
FILE* _leash_get_stdout(void) {
    return stdout;
}

#ifndef __linux__
/* GC stubs - just use regular malloc/free for non-Linux targets */
void GC_init(void) {
    /* No-op */
}

void* GC_malloc(size_t size) {
    void* ptr = malloc(size);
    /* Zero-initialize like GC_malloc does */
    if (ptr) {
        char* p = (char*)ptr;
        for (size_t i = 0; i < size; i++) {
            p[i] = 0;
        }
    }
    return ptr;
}

void* GC_realloc(void* ptr, size_t size) {
    return realloc(ptr, size);
}

/* clock_gettime stub - use regular time functions */
int clock_gettime(int clk_id, struct timespec* tp) {
    struct timeval tv;
    if (gettimeofday(&tv, NULL) != 0) {
        return -1;
    }
    tp->tv_sec = tv.tv_sec;
    tp->tv_nsec = tv.tv_usec * 1000;
    return 0;
}
#endif

/* __chkstk - Windows stack checking function generated by LLVM */
#ifdef _WIN32
void __chkstk(void) {
    /* No-op */
}
#endif
