/*
 * Minimal stub implementations for native Windows compilation.
 * Provides Leash I/O stubs using MSVC runtime.
 * 
 * Note: The Leash custom GC (gc.c) is linked separately,
 * so these stubs don't need to provide GC functions.
 */

#include <stdlib.h>
#include <stdio.h>
#include <conio.h>
#include <windows.h>
#include <signal.h>
#include <stdint.h>
#include "gc.h"

FILE* _leash_get_stdout(void) {
    return stdout;
}

/* __chkstk - Windows stack checking function generated by LLVM */
void __chkstk(void) {
    /* No-op */
}

/* clock_gettime stub for cross-compilation (MinGW does not provide it).
 * The Leash IR declares clock_gettime as i32(i32, {i64,i64}*), so the
 * second argument is a pointer to two i64 (tv_sec, tv_nsec).
 * We provide the same ABI via a struct of two int64_t.
 */
struct leash_timespec {
    int64_t tv_sec;
    int64_t tv_nsec;
};

int clock_gettime(int clk_id, struct leash_timespec *tp) {
    (void)clk_id;
    FILETIME ft;
    GetSystemTimeAsFileTime(&ft);
    ULARGE_INTEGER uli;
    uli.LowPart = ft.dwLowDateTime;
    uli.HighPart = ft.dwHighDateTime;
    /* 116444736000000000 = 100-ns intervals between 1601-01-01 and 1970-01-01 */
    uli.QuadPart -= 116444736000000000ULL;
    tp->tv_sec  = (int64_t)(uli.QuadPart / 10000000ULL);
    tp->tv_nsec = (int64_t)((uli.QuadPart % 10000000ULL) * 100);
    return 0;
}

/* Read a single key without waiting for Enter */
int leash_keyget(void) {
    return _getch();
}

/* ---- Threading support (Windows) ---- */

/* Maximum number of worker threads. Overridable at runtime through the
   LEASH_MAX_WORKERS environment variable (clamped to [1, 4096]); the
   default stays 64. Resolved once on first use under the worker-table
   lock, so every thread sees the same cap. */
static int _leash_max_workers = 0;   /* 0 = not resolved yet */

/* Global interrupted flag for worker threads */
static volatile int _leash_interrupted = 0;

/* Thread handles for all spawned workers. The table grows to the resolved
   cap on first use and is reused after leash_wait_for_workers() resets
   the counter, so repeated spawn/wait cycles do not leak. */
static HANDLE *_leash_workers = NULL;
static int _leash_workers_cap = 0;
static int _leash_num_workers = 0;
/* Guards the worker table and counter: a worker running an async fn can
   itself spawn children, so leash_spawn_worker() is not main-thread-only.
   SRWLOCK is statically initialized — no init race. */
static SRWLOCK _leash_worker_lock = SRWLOCK_INIT;

static int leash_max_workers(void) {
    int n = _leash_max_workers;
    if (n > 0) return n;
    long v = 64;
    const char *env = getenv("LEASH_MAX_WORKERS");
    if (env && *env) {
        char *endp = NULL;
        long parsed = strtol(env, &endp, 10);
        if (endp && *endp == '\0' && parsed >= 1) v = parsed;
    }
    if (v > 4096) v = 4096;
    AcquireSRWLockExclusive(&_leash_worker_lock);
    if (_leash_max_workers <= 0) _leash_max_workers = (int)v;
    ReleaseSRWLockExclusive(&_leash_worker_lock);
    return _leash_max_workers;
}

/* Signal handler for Ctrl+C / SIGINT */
static void _leash_signal_handler(int sig) {
    (void)sig;
    _leash_interrupted = 1;
}

/* Thread wrapper to match pthread's void* (*)(void*) signature */
typedef struct {
    void* (*func)(void*);
    void* arg;
} WorkerArgs;

static DWORD WINAPI _leash_thread_wrapper(LPVOID lpParam) {
    WorkerArgs* wa = (WorkerArgs*)lpParam;
    wa->func(wa->arg);
    free(wa);
    return 0;
}

/* Common spawn path. `quiet` suppresses the cap-reached report: the
 * async/await expansion runs the task inline when the cap is hit, which
 * is a correct (only non-parallel) fallback — so hitting the cap there
 * is not an error and must not print to stderr. Plain `spawn` keeps the
 * loud report, because a silently dropped task IS an error for the user.
 * Returns 0 when the thread was spawned; 1 when the cap was reached
 * (the caller runs the task inline); -1 on hard failure. */
static int lsh_spawn_worker_internal(void* (*func)(void*), void* arg, int quiet) {
    int cap = leash_max_workers();

    AcquireSRWLockExclusive(&_leash_worker_lock);
    int full = (_leash_num_workers >= cap);
    ReleaseSRWLockExclusive(&_leash_worker_lock);
    if (full) {
        if (!quiet) {
            fprintf(stderr, "error: Maximum number of worker threads (%d) reached\n", cap);
        }
        return 1;
    }

    /* Register the argument as a GC root so it isn't collected before the
       worker thread starts and has a chance to load it.  The worker wrapper
       (generated code) will unregister it after loading the parameters. */
    if (arg) {
        leash_gc_register_root(arg);
    }

    /* Switch the GC to locked (multi-threaded) mode before the thread
       exists — single-threaded programs keep the lock-free alloc path. */
    leash_gc_thread_spawned();

    /* We need a wrapper because Windows threads have a different signature */
    WorkerArgs* wa = (WorkerArgs*)malloc(sizeof(WorkerArgs));
    if (!wa) {
        fprintf(stderr, "error: Out of memory\n");
        return -1;
    }
    wa->func = func;
    wa->arg = arg;

    HANDLE thread = CreateThread(NULL, 0, _leash_thread_wrapper, wa, 0, NULL);
    if (thread == NULL) {
        fprintf(stderr, "error: Failed to create worker thread\n");
        free(wa);
        return -1;
    }

    AcquireSRWLockExclusive(&_leash_worker_lock);
    if (_leash_num_workers < cap) {
        /* Grow the table on first use (or if the resolved cap grew). */
        if (_leash_num_workers >= _leash_workers_cap) {
            HANDLE *nt = (HANDLE *)realloc(
                _leash_workers, (size_t)cap * sizeof(HANDLE));
            if (nt) {
                _leash_workers = nt;
                _leash_workers_cap = cap;
            }
        }
        if (_leash_num_workers < _leash_workers_cap) {
            _leash_workers[_leash_num_workers++] = thread;
            thread = NULL;
        }
    }
    ReleaseSRWLockExclusive(&_leash_worker_lock);

    if (thread != NULL) {
        /* The table could not grow between the cap check and here. The
           thread is running and will finish; it just cannot be joined. */
        CloseHandle(thread);
    }
    return 0;
}

/* Spawn a worker thread. Reports the worker cap as an error (plain
 * `spawn` would silently lose the task).
 * Returns 0 on success, non-zero on failure.
 */
int leash_spawn_worker(void* (*func)(void*), void* arg) {
    return lsh_spawn_worker_internal(func, arg, 0);
}

/* Try to spawn a worker thread without reporting the cap as an error.
 * Used by the async/await expansion: when the worker cap is reached the
 * generated wrapper runs the task inline — correct, just non-parallel —
 * so hitting the cap is not an error and must not pollute stderr.
 * Returns 0 when spawned, non-zero otherwise (run the task inline). */
int leash_try_spawn_worker(void* (*func)(void*), void* arg) {
    return lsh_spawn_worker_internal(func, arg, 1);
}

/* Check if the program has been interrupted (Ctrl+C). Returns 1 if interrupted, 0 otherwise. */
int leash_is_interrupted(void) {
    return _leash_interrupted;
}

/* Set up the interrupt signal handler (SIGINT -> Ctrl+C). */
void leash_setup_interrupt_handler(void) {
    signal(SIGINT, _leash_signal_handler);
}

/* Wait for all spawned worker threads to finish. */
void leash_wait_for_workers(void) {
    AcquireSRWLockExclusive(&_leash_worker_lock);
    int n = _leash_num_workers;
    ReleaseSRWLockExclusive(&_leash_worker_lock);
    for (int i = 0; i < n; i++) {
        WaitForSingleObject(_leash_workers[i], INFINITE);
        CloseHandle(_leash_workers[i]);
    }
    AcquireSRWLockExclusive(&_leash_worker_lock);
    _leash_num_workers = 0;
    ReleaseSRWLockExclusive(&_leash_worker_lock);
}

/* ---- Native source-level debugger (leash dbg) ----
 * Same protocol as the POSIX stub in cross_compile_stubs.c; see that file
 * for the contract. Uses a CRITICAL_SECTION to serialize the prompt. */
#include <string.h>
#include <stdarg.h>

#define LSH_DBG_MAX_BREAKS 128
#define LSH_DBG_LINE_LEN   1024

static int     lsh_dbg_state = -1;
static int     lsh_dbg_running = 0;
static int     lsh_dbg_breaks[LSH_DBG_MAX_BREAKS];
static int     lsh_dbg_nbreaks = 0;
static char    lsh_dbg_src[4096] = "";
static FILE   *lsh_dbg_src_file = NULL;
static CRITICAL_SECTION lsh_dbg_cs;
static int     lsh_dbg_cs_init = 0;

static void lsh_dbg_trim(char *s) {
    size_t n = strlen(s);
    while (n > 0 && (s[n - 1] == '\n' || s[n - 1] == '\r')) s[--n] = '\0';
}

static void lsh_dbg_lazy_init(void) {
    if (lsh_dbg_state != -1) return;
    lsh_dbg_state = 0;
    const char *env = getenv("LEASH_DBG");
    if (!env || !env[0] || (env[0] == '0' && env[1] == '\0')) return;
    lsh_dbg_state = 1;

    if (!lsh_dbg_cs_init) {
        InitializeCriticalSection(&lsh_dbg_cs);
        lsh_dbg_cs_init = 1;
    }

    const char *src = getenv("LEASH_DBG_SRC");
    if (src && src[0]) {
        strncpy(lsh_dbg_src, src, sizeof(lsh_dbg_src) - 1);
        lsh_dbg_src_file = fopen(lsh_dbg_src, "r");
    }

    const char *b = getenv("LEASH_DBG_BREAKS");
    if (b && b[0]) {
        const char *p = b;
        const char *end;
        while (*p && lsh_dbg_nbreaks < LSH_DBG_MAX_BREAKS) {
            long v = strtol(p, (char **)&end, 10);
            if (end == p) {
                p++; /* garbage byte: skip it, never spin */
            } else {
                if (v > 0) lsh_dbg_breaks[lsh_dbg_nbreaks++] = (int)v;
                p = end;
            }
            while (*p == ',' || *p == ' ') p++;
        }
    }
    if (getenv("LEASH_DBG_RUN")) lsh_dbg_running = 1;

    fprintf(stdout, "[leash-dbg] breakpoint locations: %d\n", lsh_dbg_nbreaks);
    fprintf(stdout, "[leash-dbg] h for help, s/Enter to step, c to continue\n");
    fflush(stdout);
}

static int lsh_dbg_is_breakpoint(int line) {
    for (int i = 0; i < lsh_dbg_nbreaks; i++) {
        if (lsh_dbg_breaks[i] == line) return 1;
    }
    return 0;
}

static void lsh_dbg_print_source(int line) {
    if (!lsh_dbg_src_file) return;
    rewind(lsh_dbg_src_file);
    char buf[256];
    long cur = 1;
    while (fgets(buf, sizeof(buf), lsh_dbg_src_file)) {
        if (cur == (long)line) {
            lsh_dbg_trim(buf);
            fprintf(stdout, "       %ld | %s\n", cur, buf);
            break;
        }
        cur++;
    }
}

static void lsh_dbg_help(void) {
    fprintf(stdout,
        "[leash-dbg] commands:\n"
        "  s | n | <Enter>  step to the next statement\n"
        "  c                continue (run until the next breakpoint)\n"
        "  b <line>         set a breakpoint\n"
        "  d <line>         delete a breakpoint\n"
        "  l                list breakpoints\n"
        "  h                this help\n"
        "  q                quit the program now\n");
    fflush(stdout);
}

void __leash_dbg_stmt(const char *func, int line) {
    lsh_dbg_lazy_init();
    if (!lsh_dbg_state || line <= 0) return;

    if (!lsh_dbg_cs_init) {
        InitializeCriticalSection(&lsh_dbg_cs);
        lsh_dbg_cs_init = 1;
    }
    EnterCriticalSection(&lsh_dbg_cs);

    if (lsh_dbg_running && !lsh_dbg_is_breakpoint(line)) {
        LeaveCriticalSection(&lsh_dbg_cs);
        return;
    }

    if (lsh_dbg_running && lsh_dbg_is_breakpoint(line)) {
        fprintf(stdout, "[leash-dbg] hit breakpoint at line %d\n", line);
        lsh_dbg_running = 0;
    }

    fprintf(stdout, "[leash-dbg] --> %s:%d in %s\n",
            lsh_dbg_src[0] ? lsh_dbg_src : "?", line, func ? func : "?");
    lsh_dbg_print_source(line);
    fflush(stdout);

    char cmd[LSH_DBG_LINE_LEN];
    for (;;) {
        fprintf(stdout, "(dbg) ");
        fflush(stdout);
        if (!fgets(cmd, sizeof(cmd), stdin)) {
            lsh_dbg_running = 1;
            break;
        }
        lsh_dbg_trim(cmd);
        if (cmd[0] == '\0' || strcmp(cmd, "s") == 0 || strcmp(cmd, "n") == 0 ||
                strcmp(cmd, "step") == 0) {
            break;
        }
        if (strcmp(cmd, "c") == 0 || strcmp(cmd, "continue") == 0) {
            lsh_dbg_running = 1;
            break;
        }
        if (strcmp(cmd, "h") == 0 || strcmp(cmd, "help") == 0) {
            lsh_dbg_help();
            continue;
        }
        if (strcmp(cmd, "l") == 0 || strcmp(cmd, "list") == 0) {
            fprintf(stdout, "[leash-dbg] %d breakpoint(s):", lsh_dbg_nbreaks);
            for (int i = 0; i < lsh_dbg_nbreaks; i++)
                fprintf(stdout, " %d", lsh_dbg_breaks[i]);
            fprintf(stdout, "\n");
            fflush(stdout);
            continue;
        }
        if (strcmp(cmd, "q") == 0 || strcmp(cmd, "quit") == 0) {
            fprintf(stdout, "[leash-dbg] quitting\n");
            fflush(stdout);
            _exit(0);
        }
        if (cmd[0] == 'b' || cmd[0] == 'd') {
            if (cmd[1] == ' ' || cmd[1] == '\t') {
                int v = atoi(cmd + 2);
                if (v <= 0) {
                    fprintf(stdout, "[leash-dbg] bad line number\n");
                    fflush(stdout);
                    continue;
                }
                if (cmd[0] == 'b') {
                    if (lsh_dbg_nbreaks < LSH_DBG_MAX_BREAKS &&
                            !lsh_dbg_is_breakpoint(v)) {
                        lsh_dbg_breaks[lsh_dbg_nbreaks++] = v;
                    }
                    fprintf(stdout, "[leash-dbg] breakpoint set at line %d\n", v);
                } else {
                    for (int i = 0; i < lsh_dbg_nbreaks; i++) {
                        if (lsh_dbg_breaks[i] == v) {
                            lsh_dbg_breaks[i] = lsh_dbg_breaks[--lsh_dbg_nbreaks];
                            break;
                        }
                    }
                    fprintf(stdout, "[leash-dbg] breakpoint cleared at line %d\n", v);
                }
                fflush(stdout);
                continue;
            }
        }
        fprintf(stdout, "[leash-dbg] unknown command (h for help)\n");
        fflush(stdout);
    }

    LeaveCriticalSection(&lsh_dbg_cs);
}
