/*
 * Minimal stub implementations for native Windows compilation.
 * Provides Leash I/O stubs using MSVC runtime.
 * 
 * Note: The Leash custom GC (gc.c) is linked separately,
 * so these stubs don't need to provide GC functions.
 */

#include <stdlib.h>
#include <stdio.h>

FILE* _leash_get_stdout(void) {
    return stdout;
}

/* __chkstk - Windows stack checking function generated by LLVM */
void __chkstk(void) {
    /* No-op */
}
